var calldetails = [
  {
    "name": "Tom",
    "image": "asset/guys.jpg",
    "time": "May 9, 16:11",
    "callstatus": "incoming",
    "audio": true,
  },
  {
    "name": "Mark",
    "image": "asset/guys2.jpg",
    "time": "May 9, 16:11",
    "callstatus": "outgoing",
    "audio": true,
  },
  {
    "name": "Bob",
    "image": "asset/babyy.jpg",
    "time": "May 9, 16:11",
    "callstatus": "missed",
    "audio": true,
  },
  {
    "name": "Alice",
    "image": "asset/lady.jpeg",
    "time": "May 9, 16:11",
    "callstatus": "outgoing",
    "audio": false,
  },
  {
    "name": "Mary",
    "image": "asset/wapplogo.png",
    "time": "May 9, 16:11",
    "callstatus": "missed",
    "audio": false,
  },
  {
    "name": "Jim",
    "image": "asset/glass.png",
    "time": "May 9, 16:11",
    "callstatus": "incoming",
    "audio": true,
  },
  {
    "name": "Rob",
    "image": "asset/guys.jpg",
    "time": "May 9, 16:11",
    "callstatus": "outgoing",
    "audio": true,
  },
  {
    "name": "Larry",
    "image": "asset/guys2.jpg",
    "time": "May 9, 16:11",
    "callstatus": "missed",
    "audio": true,
  },
  {
    "name": "Pop",
    "image": "asset/babyy.jpg",
    "time": "May 9, 16:11",
    "callstatus": "outgoing",
    "audio": false,
  },
  {
    "name": "Jason",
    "image": "asset/glass.png",
    "time": "May 9, 16:11",
    "callstatus": "missed",
    "audio": false,
  },
];